
delete from public.services where slug like 'new-service-%';

insert into public.services (slug, title, summary, description, bullets, icon, number_label, image_url, sort_order, visible) values
('interior-design','Interior Design','Thoughtful interiors that balance aesthetics, functionality and the way you live or work.','We create thoughtful interiors that balance aesthetics, functionality and the way you live or work. Our design process brings together space planning, concept development, moodboards, material selections, colour palettes, lighting and 3D visualisation to create a clear design direction for your space.',array['Space Planning','Concept Development','Moodboards & Material Selection','Colour & Finishes','Lighting Design','3D Renders & Visualisation','Furniture & Styling'],'Home','01','https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',1,true),
('renovation-construction','Renovation & Construction','Carefully managed renovation and construction works, from preparation to final handover.','We transform existing spaces through carefully managed renovation and construction works, combining design thinking with practical on-site execution. Whether you''re refreshing a single room or undertaking a complete property transformation, we coordinate the process from preparation and procurement to finishes and final handover.',array['Interior Renovations','Construction Management','Project Management','Procurement & Material Sourcing','Gypsum & Ceiling Works','Tiling & Flooring','Painting & Finishes','Electrical & Plumbing Coordination'],'HardHat','02','https://images.unsplash.com/photo-1503174971373-b1f69850bded?auto=format&fit=crop&w=1200&q=80',2,true),
('custom-interiors','Custom Interiors & Fittings','Bespoke elements that bring character, functionality and cohesion to your space.','We design and create custom elements that bring character, functionality and cohesion to your space. From kitchens and wardrobes to feature walls and bespoke furniture, every detail is considered to complement the overall design of your interior.',array['Custom Kitchens','Bathroom Design & Renovation','Wardrobes & Storage','Custom Furniture','TV Walls & Feature Walls','Wainscoting','Fluted & Decorative Wall Treatments'],'Armchair','03','https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1200&q=80',3,true),
('commercial-hospitality','Commercial & Hospitality Spaces','Commercial environments designed to work, feel distinctive and leave a lasting impression.','We create commercial environments that are designed to work, feel distinctive and leave a lasting impression. From offices and retail spaces to hospitality and Airbnb properties, we combine functionality, brand identity and thoughtful design to create spaces that people want to experience.',array['Office Fit-outs','Retail & Commercial Interiors','Airbnb Styling & Transformation','Hospitality Spaces','Space Planning','Interior Renovations','Custom Fixtures & Fittings'],'Building2','04','https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',4,true)
on conflict (slug) do nothing;

insert into public.testimonials (quote, name, detail, project_name, sort_order, visible) values
('Kloche understood our home better than we did. Six months on, we still notice small details they got exactly right.','Wanjiru & Kevin M.','Kileleshwa Residency','Kileleshwa Residency',1,true),
('They managed contractors, budget and our indecision with complete calm. The reveal genuinely made my mother cry.','Aisha O.','Westlands Airbnb','Westlands Airbnb',2,true),
('Our office finally feels like the studio we tell clients we are. Staff arrive earlier — that''s the review.','Daniel Kimani','Founder, Gigiri Executive Offices','Gigiri Executive Offices',3,true);

insert into public.page_sections (page_key, section_key, kind, eyebrow, title, body, image_url, sort_order, visible) values
('about','hero','hero','About','Meet the Founder','Keith Locho — Founder & Creative Director, Kloche Interiors & Construction.','https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=80',1,true),
('about','founder','richtext','Meet the Founder','Keith Locho','Founder & Creative Director','https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=80',2,true),
('about','philosophy','richtext','Our Philosophy','Design that feels like home','We believe a well-designed space should feel considered, warm and unmistakably yours.','',3,true),
('services','hero','hero','Services','Our key services','Design, renovation, custom interiors and commercial fit-outs — delivered end to end.','',1,true),
('portfolio','hero','hero','Portfolio','Spaces We''ve Transformed.','A selection of homes, offices and hospitality spaces designed by our studio.','',1,true),
('pricing','hero','hero','Investment Guide','Investing in Spaces That Last','Transparent guide rates for design, renovation and custom interiors.','https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1400&q=80',1,true),
('contact','hero','hero','Contact','Let''s talk about your space','Tell us about your project and we''ll come back to you within one working day.','https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=1400&q=80',1,true);
